/* 00_bootstrap.sql
   Environment bootstrap for Financial Data Ingestion modular pipeline.
*/
USE DATABASE FIN_INGEST;
USE SCHEMA RAW;

CREATE SCHEMA IF NOT EXISTS FIN_INGEST.RAW;
CREATE SCHEMA IF NOT EXISTS FIN_INGEST.CANON;
CREATE SCHEMA IF NOT EXISTS FIN_INGEST.OPS;
