/* 00_bootstrap.sql
   Environment bootstrap for Financial Data Ingestion modular pipeline.
*/
CREATE DATABASE IF NOT EXISTS FIN_INGEST;
USE DATABASE FIN_INGEST;

CREATE SCHEMA IF NOT EXISTS FIN_INGEST.RAW;
CREATE SCHEMA IF NOT EXISTS FIN_INGEST.CANON;
CREATE SCHEMA IF NOT EXISTS FIN_INGEST.OPS;

USE SCHEMA FIN_INGEST.RAW;
