/* 08_smoke_tests.sql
   Minimal smoke checks post-run.
*/
USE DATABASE FIN_INGEST;

SELECT 'CAN_TXN' AS object_name, COUNT(*) AS row_count FROM FIN_INGEST.CANON.CAN_TXN
UNION ALL
SELECT 'CAN_TXN_LINE', COUNT(*) FROM FIN_INGEST.CANON.CAN_TXN_LINE
UNION ALL
SELECT 'CAN_TXN_ANOMALY', COUNT(*) FROM FIN_INGEST.CANON.CAN_TXN_ANOMALY;

SELECT * FROM FIN_INGEST.OPS.VW_CANON_COUNTS ORDER BY client_id, source_system;
SELECT * FROM FIN_INGEST.OPS.VW_ANOMALY_COUNTS ORDER BY anomaly_count DESC, client_id, source_system;
SELECT * FROM FIN_INGEST.OPS.VW_LOAD_AUDIT_SUMMARY ORDER BY latest_load_ts DESC;
